---
- name: Ansible Facts Demo
  hosts: routers
  tasks:
    # - name: Print Ansible Facts
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ ansible_facts }}"
          # - "{{ ansible_facts.distribution }}"
          # - "{{ ansible_facts.hostname }}"
          # - "{{ ansible_facts.interfaces }}"

    # - name: Configure CSR interface
    #   when: ansible_facts.net_model == "CSR1000V"
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet1
    #         description: mgmt interface CSR1000V
    #   register: intf_conf
    
    # - name: Configure IOSv interface
    #   when: ansible_facts.net_model != "CSR1000V"
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/0
    #         description: description for IOSv
    #   register: intf_conf

    # - debug: msg="{{ intf_conf }}"
    
    - name: Configure Routers interface
      cisco.ios.ios_interfaces:
        config:
          - name: "{{mgmt_int_list.get(ansible_facts.net_model).name}}"
            description: "{{mgmt_int_list.get(ansible_facts.net_model).description}}"
      register: intf_conf

    - debug: msg="{{ intf_conf.commands }}"