---
- name: HostVars Demo
  hosts: r3
  gather_facts: false
  tasks:
    # - name: Print Pre-HostVars
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ hostvars }}"
    
    # - name: Configure CSR interface
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet1
    #         description: Desc for CSR1000V mgmt interface 
    #   register: csr_conf

    #- debug: msg="{{ csr_conf }}"
  
    # - name: Print Post-HostVars
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ hostvars[inventory_hostname]['csr_conf'] }}"
    
    - name: Configure domain
      cisco.ios.ios_config:
        lines: "ip domain name {{hostvars['r2']['dc1_domain']}}"
      register: dom_conf
    
    - debug: msg="{{ dom_conf }}"