---
- name: Block, Rescue and Always
  hosts: routers
  # gather_facts: false
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    # - name: Gather Interfaces
    #   cisco.ios.ios_interfaces:
    #     state: gathered
    #   register: intf_config
    
    ############## Block for vIOS Devices ##############
    - name: Block for vIOS Devices
      when: ansible_facts.net_model == 'IOSv'
      block:
        - name: Management Interface Config vIOS
          cisco.ios.ios_interfaces:
            config:
              - name: GigabitEthernet0/0
                description: vIOS MGMT
          register: intf_config
        
        #### Invalid config line ###
        - name: Invalid config line
          cisco.ios.ios_config:
            lines: abc
      rescue:
        - name: Print fail message
          ansible.builtin.debug:
            msg: "Task has failed"
      always:
        - name: Print facts
          ansible.builtin.debug:
            msg: 
              - "{{ intf_config }}"

    ############## Block for CSR1000V Devices ##############
    - name: Block for CSR1000V Devices
      when: ansible_facts.net_model == 'CSR1000V'
      block:
        - name: Management Interface Config CSR1000V
          cisco.ios.ios_interfaces:
            config:
              - name: GigabitEthernet1
                description: CSR1000V MGMT
          register: intf_config
        
        #### Invalid config line ###
        - name: Invalid config line
          cisco.ios.ios_config:
            lines: abc

        - name: Print facts
          ansible.builtin.debug:
            msg: 
              - "{{ intf_config }}"
      rescue:
        - name: Print fail message
          ansible.builtin.debug:
            msg: "Task has failed"

    - name: Print End of the Play
      ansible.builtin.debug:
            msg: "End of the Play"