---
- name: Assert Demo
  hosts: routers
  # gather_facts: false
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
    
    ############## Block for vIOS Devices ##############
    - name: Block for vIOS Devices
      block:
        - name: Assert Demo
          ansible.builtin.assert:
            that: 
              # - ansible_facts.net_model == 'IOSv'
              # - inventory_hostname == 'r1'
              - ansible_facts.net_model == 'IOSv' or inventory_hostname == 'r1'
            
            fail_msg: "Not vIOS"
            success_msg: "Device is vIOS"

        - name: Management Interface Config vIOS
          cisco.ios.ios_interfaces:
            config:
              - name: GigabitEthernet0/0
                description: vIOS MGMT
          register: intf_config

        - name: Print intf config
          ansible.builtin.debug:
            msg: 
              - "{{ intf_config }}"

      rescue:
        - name: Print fail message
          ansible.builtin.debug:
            msg: "Task has failed"
    
        

    