ip_domain_name: from_r2_host_vars.com
dc1_domain: dc1_from_r2.com
interface_list:
      - name: GigabitEthernet0/2
        desc: Gi2_desc
        ip: 100.1.2.2
        mask: 255.255.255.0
      - name: GigabitEthernet0/3
        desc: Gi3_desc
        ip: 100.1.3.3
        mask: 255.255.255.0