---
- name: Jinja2 Template Demo
  hosts: routers
  gather_facts: false
  tasks:
    # - name: Generate Conf 
    #   ansible.builtin.template:
    #     src: device_conf.j2
    #     dest: "demo_files/{{ inventory_hostname }}_device_conf.txt"
    
    # - debug: msg="{{ groups }}"

      - name: Send Config to Cisco 
        cisco.ios.ios_config:
          #lines: "{{ lookup('template', 'templates/device_conf.j2') }}"
          lines: "{{ lookup('template', 'device_conf.j2') }}"
        register: ios_conf

      - debug: msg="{{ ios_conf }}"