---
- name: Jinja2 Template Demo
  hosts: routers
  gather_facts: false
  tasks:
  ########## template ##################
    # - name: Generate Conf 
    #   ansible.builtin.template:
    #     src: templates/device_conf.j2
    #     dest: "demo_files/{{ inventory_hostname }}_device_conf.txt"
    
    # - debug: msg="{{ groups }}"

############ ios template ####################
      # - name: Send Config to Cisco 
      #   cisco.ios.ios_config:
      #     #lines: "{{ lookup('template', 'templates/device_conf.j2') }}"
      #     lines: "{{ lookup('template', 'device_conf.j2') }}"
      #   register: ios_conf

      # - debug: msg="{{ ios_conf }}"

########### for loop #########################
    # - name: Template for for_loop 
    #   ansible.builtin.set_fact:
    #     route_list: "{{ dest_subs | zip_longest(dest_gws) | list }}"
      
    # - debug: msg="{{ route_list }}"

    # - name: Generate Conf 
    #   ansible.builtin.template:
    #     src: templates/for_loop.j2
    #     dest: "demo_files/{{ inventory_hostname }}_ip_route_conf.txt"
    
    # - debug: msg="{{ groups }}"

    ########## jinja2 include option ##################
    # - name: Template for for_loop 
    #   ansible.builtin.set_fact:
    #     route_list: "{{ dest_subs | zip_longest(dest_gws) | list }}"

    # - name: Jinja2 include option
    #   ansible.builtin.template:
    #     src: templates/include_demo.j2
    #     dest: "demo_files/{{ inventory_hostname }}_include_all_conf.txt"
    
    ########## Embeb jinja2 code into ansible ##################
    - name: Create list of interface names 
      ansible.builtin.set_fact:
        intf_lst: "{{ interface_list | map(attribute='name')}}"
    
    - debug: msg="{{ intf_lst }}"

    - name: Jinja2 Code
      ansible.builtin.set_fact:
        intf_list: |
                {% set intf_name_list = [] %}
                {% for intf_details in interface_list %}
                {% set intf_name = intf_details.get('name') %}
                {% set intf_name_list = intf_name_list.append(intf_name) %}
                {% endfor %}
                {{ intf_name_list }}
    
    - debug: msg="{{ intf_list }}"