- name: Include vs Import
  hosts: localhost
  gather_facts: false
  tasks:
    - name: User Input
      ansible.builtin.pause:
        prompt: Enter Username
      register: p_user

    - name: User Input
      ansible.builtin.pause:
        prompt: Enter password
        echo: false
      register: p_password

    - name: Set fact
      ansible.builtin.set_fact:
        new_user: "{{ p_user.user_input }}"
        new_password: "{{ p_password.user_input }}"
    
    - name: Set fact v
      ansible.builtin.set_fact:
        v: 0

      ######## Include Task ###########
    - name: Include Task
      ansible.builtin.include_tasks: user_conf.yml
      loop: [a1, a2, a3]
      
      ######## Import Task ###########
    # - name: Import Task
    #   ansible.builtin.import_tasks: user_conf.yml
      