---
- name: Task Options- ignore_errors
  hosts: routers:!r1
  gather_facts: false
  tasks:
    - name: Gather Static Route from R1
      cisco.ios.ios_static_routes:
        state: gathered
      delegate_to: r1
      run_once: true
      register: r1_static_route

    - name: Print R1 Output
      ansible.builtin.debug:
        msg: "{{ r1_static_route }}"
      run_once: true

    ######### ignore_errors example
    - name: Interface Config
      cisco.ios.ios_interfaces:
        config: 
          - name: GigabitEthernet0/2
            description: new_desc1
        state: merged
      ignore_errors: true

      ###############################
    - name: Config Static Route
      cisco.ios.ios_static_routes:
        config: "{{ r1_static_route.gathered}}"
        state: merged
      register: router_config
    
    - name: Print R2 Output
      ansible.builtin.debug:
        msg: "{{ router_config }}"