---
- name: PyATS Parsers Demo
  hosts: r3
  gather_facts: false
  tasks:
    # - name: Ansible CLI Parse
    #   ansible.utils.cli_parse:
    #     command: show version
    #     parser:
    #       name: ansible.netcommon.pyats
    #     set_fact: sh_ver
    #   register: show_output
    
    - name: Ansible CLI Parse
      ansible.utils.cli_parse:
        command: show ip interface brief
        parser:
          name: ansible.netcommon.pyats
        set_fact: sh_ver
      register: show_output

    - name: Print Output
      ansible.builtin.debug:
        msg: 
          - "{{ show_output }}"
       