---
- name: Cisco ios_interfaces module
  hosts: r2
  gather_facts: false
  tasks:
  # ########## gathered ###########
  #   - name: Interface Config
  #     cisco.ios.ios_interfaces:
  #       state: gathered
  #     register: intf_conf
    
  #   - name: Print intf config
  #     ansible.builtin.debug:
  #       msg: "{{ intf_conf.gathered }}"

    # ########## merged ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/2
    #         description: new_desc
    #         mtu: 9600
    #         enabled: true
    #     state: merged
    #   register: intf_conf

    # ########## replaced ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/2
    #         description: new_desc1
    #         mtu: 1024
    #         enabled: true
    #     state: replaced
    #   register: intf_conf
    
    #   ########## overridden ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/0
    #       - name: GigabitEthernet0/2
    #         description: new_desc1
    #         mtu: 1024
    #         enabled: true
    #     state: overridden
    #   register: intf_conf
    
     ########## rendered ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/0
    #       - name: GigabitEthernet0/2
    #         description: new_desc1
    #         mtu: 1024
    #         enabled: true
    #     state: rendered
    #   register: intf_conf

    # - name: Print intf config
    #   ansible.builtin.debug:
    #     msg: "{{ intf_conf.rendered}}"

    ########## parsed ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     running_config: "{{ lookup('file', 'backup/r2.conf')}}"
    #     state: parsed
    #   register: intf_conf
    
    #  ########## template ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/3
    #         template: demo-temp1
    #     state: merged
    #   register: intf_conf

    # - name: Print intf config
    #   ansible.builtin.debug:
    #     msg: "{{ intf_conf }}"

    ########## deleted ###########
    # - name: Interface Config
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: GigabitEthernet0/1
    #       - name: GigabitEthernet0/2
    #     state: deleted
    #   register: intf_conf

 ########## purged ###########
    - name: Interface Config
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback200 
        state: purged
      register: intf_conf

    - name: Print intf config
      ansible.builtin.debug:
        msg: "{{ intf_conf }}"