---
- name: Cisco ios_l3_interfaces module
  hosts: r2
  gather_facts: false
  tasks:
  # ########## gathered ###########
    # - name: Gather L3 Interface Config
    #   cisco.ios.ios_l3_interfaces:
    #     state: gathered
    #   register: intf_conf

    ########## parsed ###########
    # - name: Parsed L3 Interface Config
    #   cisco.ios.ios_l3_interfaces:
    #     running_config: "{{ lookup('file', 'backup/r2.conf')}}"
    #     state: parsed
    #   register: intf_conf

  ########## rendered ###########
    # - name: Rendered L3 Interface Config
    #   cisco.ios.ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet0/1
    #         ipv4:
    #           - address: 10.10.10.1/28
    #     state: rendered
    #   register: intf_conf

    # - name: Print intf config
    #   ansible.builtin.debug:
    #     msg: "{{ intf_conf }}"
    

    # ########## merged ###########
    # - name: Merged L3 Interface Config
    #   cisco.ios.ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet0/1
    #         ipv4:
    #           - address: 10.10.10.2/28
    #     state: merged
    #   register: intf_conf

    # - name: Print intf config
    #   ansible.builtin.debug:
    #     msg: "{{ intf_conf }}"

    # ########## replaced ###########
    # - name: Replaced L3 Interface Config
    #   cisco.ios.ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet0/1
    #         ipv4:
    #           - address: 10.10.10.1/28
    #     state: replaced
    #   register: intf_conf

    # - name: Print intf config
    #   ansible.builtin.debug:
    #     msg: "{{ intf_conf }}"
    
    #   ########## overridden ###########
    # - name: Overridden L3 Interface Config
    #   cisco.ios.ios_l3_interfaces:
    #     config:
    #       - name: GigabitEthernet0/0
    #         ipv4:
    #           - address: 192.168.117.62/24
    #       - name: GigabitEthernet0/1
    #         ipv4:
    #           - address: 10.10.10.1/28
    #     state: overridden
    #   register: intf_conf

    # - name: Print intf config
    #   ansible.builtin.debug:
    #     msg: "{{ intf_conf }}"
    
    ########## deleted ###########
    - name: Deleted L3 Interface Config
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/1
        state: deleted
      register: intf_conf

    - name: Print intf config
      ansible.builtin.debug:
        msg: "{{ intf_conf }}"

