---
- name: Ansible Filters
  hosts: r2
  gather_facts: false
  vars:
    ospf_process_id: 2
    vrf_name: 'mgmt'
    devices: ['r1', 'r2']
  tasks:
  ########### default #############
    # - name: Print output
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ ospf_process_id | default(1, true)}}"
  
  ########### default(omit) #############
    # - name: Interface Config
    #   with_items: "{{ interface_list }}"
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: "{{item.name}}"
    #         description: "{{item.description | default(omit)}}"
    #   register: intf_config

    # - name: Print output
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ intf_config }}"

    ########## Ternary ###############
    - name: Ternary Filter
      ansible.builtin.set_fact:
        vrf_type: "{{ (vrf_name == 'mgmt') | ternary('management' , 'non-management') }}"
    
    - name: Print output
      ansible.builtin.debug:
        msg: 
          - "{{ vrf_type }}"
          - "{{ vrf_type | type_debug }}"
          - "{{ devices | type_debug }}"