---
- name: Ansible Filters
  hosts: r2
  gather_facts: false
  vars:
    ospf_process_id: 2
    vrf_name: 'mgmt'
    devices: ['r1', 'r2']
  tasks:
  ########### default #############
    # - name: Print output
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ ospf_process_id | default(1, true)}}"
  
  ########### default(omit) #############
    # - name: Interface Config
    #   with_items: "{{ interface_list }}"
    #   cisco.ios.ios_interfaces:
    #     config:
    #       - name: "{{item.name}}"
    #         description: "{{item.description | default(omit)}}"
    #   register: intf_config

    # - name: Print output
    #   ansible.builtin.debug:
    #     msg:
    #       - "{{ intf_config }}"

    ########## Ternary ###############
    # - name: Ternary Filter
    #   ansible.builtin.set_fact:
    #     vrf_type: "{{ (vrf_name == 'mgmt') | ternary('management' , 'non-management') }}"
    
    # - name: Print output
    #   ansible.builtin.debug:
    #     msg: 
    #       - "{{ vrf_type }}"
    #       - "{{ vrf_type | type_debug }}"
    #       - "{{ devices | type_debug }}"
    
    ########## dict2items, items2dict ############
    # - name: Ansible dict2items Filter
    #   ansible.builtin.debug:
    #     msg: "{{ ospf_vars | dict2items }}"
    
    # - name: Ansible dict2items Filter
    #   ansible.builtin.debug:
    #     msg: "{{ ospf_vars | dict2items(key_name='abc', value_name='cde') }}"

    # - name: Ansible items2dict Filter
    #   ansible.builtin.debug:
    #     msg: "{{interface_list | items2dict(key_name='name', value_name='ip') }}"
    
    ########## Save to_json, to_yaml ############
    # - name: Save to_json
    #   ansible.builtin.copy:
    #     #content: "{{ ospf_vars | to_json }}"
    #     #content: "{{ ospf_vars | to_nice_json }}"
    #     content: "{{ ospf_vars | to_nice_json(indent=8) }}"
    #     #dest: to_json_demo.json
    #     #dest: to_nice_json_demo.json
    #     dest: to_nice_json_ind_demo.json

    - name: Save to_yaml
      ansible.builtin.copy:
        #content: "{{ interface_list | to_yaml }}"
        content: "{{ interface_list | to_nice_yaml(indent=8) }}"
        dest: to_nice_yaml_ind_demo.yaml