- name: Publish Roles in Ansible Galaxy
  hosts: routers
  gather_facts: false
  tasks:
########  handlers ##########################
    - name: Include new Role
      when: inventory_hostname == 'r1'
      ansible.builtin.include_role:
        name: naimahassan43.intf_ip_conf
      vars:
        intf_name: GigabitEthernet0/1
        intf_address: 10.10.10.1/28
       
    - name: Include new Role
      when: inventory_hostname == 'r2'
      ansible.builtin.include_role:
        name: naimahassan43.intf_ip_conf
      vars:
        intf_name: GigabitEthernet0/1
        intf_address: 10.10.10.2/28
  