collections:
  # - name: cisco.ios
  #   version: 10.0.0
  # - name: https://github.com/ansible-collections/cisco.ios.git
  #   type: git
  #   version: v11.1.0
  - name: /home/naima/Ansible_Practice_1/19_collections_role/cisco-ios-11.1.1.tar.gz
    type: file