---
- name: Facts to CSV
  hosts: routers
  gather_facts: true
  tasks:
    - name: Print Facts
      ansible.builtin.debug:
        msg: 
          #- "{{ ansible_facts }}"
          - "{{ ansible_play_hosts }}"
    
    - name: Create Facts dict
      ansible.builtin.set_fact:
        facts_dict: "{{ facts_dict | default({}) | combine({ item: hostvars[item]['ansible_facts']})}}"
      loop: "{{ ansible_play_hosts }}"
      run_once: true
    
    - name: Print Facts dict
      ansible.builtin.debug:
        msg: "{{ facts_dict }}"